package com.clandropswebhook;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;

@ConfigGroup("clandrops")
public interface ClanDropConfig extends Config
{
	@ConfigItem(
			keyName = "webhook",
			name = "Discord Webhook URL",
			description = "The URL of the discord webhook generated by the user",
			position = 1
	)
	default String webhook()
	{
		return "";
	}

	@ConfigSection(
			name="screenshot settings",
			description = "Custom single word and regex filter lists",
			position = 2
	)
	String screenshotSettings = "Screenshot Settings";

	@ConfigItem(
			keyName = "screenshot",
			name = "Enable Screenshot",
			description = "Enable this if you want to automatically post a screenshot",
			position = 1,
			section = screenshotSettings
	)
	default boolean screenshot() {
		return false;
	}

	@ConfigItem(
			keyName = "onlyChat",
			name = "Screenshot only the chatbox",
			description = "Enable this to screenshot the chatbox only instead of the entire screen",
			position = 2,
			section = screenshotSettings
	)
	default boolean onlyChat() {
		return false;
	}

	@ConfigSection(
			name="Auto message in chat",
			description = "Writes a message in the chat for the screenshot",
			position = 3
	)
	String messageSettings = "Message Settings";

	@ConfigItem(
			keyName = "autoMessageEnabled",
			name = "Enable auto message",
			description = "Enables an auto message in the chatbox",
			section = messageSettings,
			position = 1
	)
	default boolean autoMessageEnabled() {return false;}

	@ConfigItem(
			keyName = "autoMessageDate",
			name = "Enable date post",
			description = "Enables automatic date posting in the chat",
			section = messageSettings,
			position = 2
	)
	default boolean autoMessageDate() {return false;}

	@ConfigItem(
			keyName = "autoMessage",
			name = "Auto Message",
			description = "The auto message to type",
			section = messageSettings,
			position = 3)
	default String autoMessage() {return "";}
}